import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Страница выбора вещи",
  description: "Generated by create next app",
};

export default function MenuLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
        <>
          {children}
        </>
  );
}
